### ISSUE TITLE
Provide an option to disable progress bar

### ISSUE THREAD

**Issue by arty-name** [KyleRoss/modclean#5]
I am using modclean with quite some dependencies and it removes 3384 files. I run that in a build environment with non-interactive console (Jenkins) and the progress bar indicating the removal of every file adds 3384 lines to the build console output. This is not very convenient for me.

Please provide a command line option that will prevent modclean from outputting progress indicator.

**Comment by KyleRoss** [comment]
Makes sense, I will add a switch for it.

**Comment by KyleRoss** [comment]
I added `-P` and `--no-progress` command line flags to turn off the progress bar. This has been published to NPM as version 1.2.4. Let me know if you are still running into issues.

**Comment by arty-name** [comment]
Unfortunately I did run into an issue:

	node_modules/modclean/bin/modclean.js:220
		ui.clean();
		   ^
	TypeError: undefined is not a function
	    at Object.ModCleanCLI.spinStop (node_modules/modclean/bin/modclean.js:220:12)
	    at ModClean.<anonymous> (node_modules/modclean/bin/modclean.js:157:18)
	    at ModClean.emit (events.js:107:17)
	    at node_modules/modclean/index.js:188:19
	    at f (node_modules/modclean/node_modules/glob/node_modules/once/once.js:17:25)
	    at Glob.<anonymous> (node_modules/modclean/node_modules/glob/glob.js:133:7)
	    at Glob.emit (events.js:107:17)
	    at Glob._finish (node_modules/modclean/node_modules/glob/glob.js:172:8)
	    at done (node_modules/modclean/node_modules/glob/glob.js:159:12)
	    at Glob._processGlobStar2 (node_modules/modclean/node_modules/glob/glob.js:601:12)

**Comment by KyleRoss** [comment]
Sorry, missed a deprecated function in `inquirer` during regression testing. Just published version 1.2.5 to NPM and now will work correctly.

**Comment by arty-name** [comment]
Now it works well.

Thank you for being so responsive!
